filter:
  excluded_paths:
    - 'tests/'
    - 'tools/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer update --no-interaction --no-progress
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
